[technology]
label = "Technology"

[[technology.questions]]
question = "Which of the following is an example of a programming language?"
answers = [ "Java"]
alternatives = ["Photoshop", "Acrobat Reader","Excel"]
hint = "This language is commonly used for building enterprise-level web applications."
explanation = """
    Java is a high-level, object-oriented programming language.
"""

[[technology.questions]]
question = "Which of the following is a type of computer memory?"
answers = ["RAM memory"]
alternatives = ["Keyboard memory", "Hard disk memory", "Mouse memory"]
hint = " This type of memory loses its contents when the power is turned off."
explanation = """
    RAM (Random Access Memory) is a type of computer memory that is used for temporary storage of data and program instructions.
"""

[[technology.questions]]
question = "Which of the following is a type of computer network?"
answers = ["All of the above"]
alternatives = ["WAN", "LAN", "MAN"]
hint = " This type of network connects multiple devices and allows them to share resources and data."
explanation = """
    WAN (Wide Area Network), LAN (Local Area Network), and MAN (Metropolitan Area Network) are all types of computer networks.
"""

[[technology.questions]]
question = "Which of the following is NOT an example of a web browser?"
answers = ["Microsoft Word"]
alternatives = ["Chrome", "Firefox", "Safari"]
hint = " This type of application is used for creating and editing documents."
explanation = """
    Microsoft Word is not a web browser. It is a word processing application.
"""

[[technology.questions]]
question = "Which of the following is an example of a cloud storage service?"
answers = ["Google Drive"]
alternatives = ["iTunes", "Netflix", "Skype"]
hint = "This type of service is often used for backing up data and sharing files with others."
explanation = """
    Google Drive is a cloud storage service that allows users to store and access files from anywhere with an internet connection.
"""

[[technology.questions]]
question = "Which of the following is NOT an example of a mobile operating system?"
answers = ["macOS"]
alternatives = ["Android", "iOS", "Windows"]
hint = "This type of operating system is used on smartphones and tablets."
explanation = """
   macOS is not a mobile operating system. It is a desktop operating system developed by Apple.
"""

[[technology.questions]]
question = "Which of the following is a type of computer virus?"
answers = ["Trojan"]
alternatives = ["Router", "Mouse", "Keyboard"]
hint = "This type of virus is often used for stealing sensitive data and gaining unauthorized access to systems."
explanation = """
    A Trojan is a type of computer virus that disguises itself as legitimate software.
"""

[[technology.questions]]
question = "Which of the following is an example of a search engine?"
answers = ["Yahoo"]
alternatives = ["Twitter", " Facebook", "Instagram"]
hint = "This type of service is often used for finding websites and other online resources."
explanation = """
    Yahoo is a search engine that allows users to search the web for information.
"""

[[technology.questions]]
question = "Which of the following is a type of computer peripheral?"
answers = ["Keyboard"]
alternatives = ["Hard drive", "CPU", "Motherboard"]
hint = "This type of peripheral is often used for typing and gaming."
explanation = """
    A keyboard is a type of computer peripheral used for inputting data and commands.
"""

[[technology.questions]]
question = "Which of the following is a type of computer network topology?"
answers = ["All of the above"]
alternatives = ["Bus", "Point-to-point", "Star"]
hint = "This type of topology determines how devices are connected to a network."
explanation = """
    Bus, point-to-point, and star are all types of computer network topologies.
"""

[[technology.questions]]
question = "Which of the following is a type of computer processor architecture?"
answers = ["All of the above"]
alternatives = ["ARM", "Intel", "AMD"]
hint = "This type of architecture determines the type of processor used in a computer."
explanation = """
    ARM, Intel, and AMD are all examples of computer processor architectures.
"""

[[technology.questions]]
question = "Which of the following is a type of computer port?"
answers = ["All of the above"]
alternatives = ["USB", "HDMI", "VGA"]
hint = "This type of interface allows devices to connect to a computer system."
explanation = """
    USB, HDMI, and VGA are all types of computer ports.
"""

[[technology.questions]]
question = "Which of the following is a type of computer display?"
answers = ["CRT"]
alternatives = [" DVD", "USB", "HDMI"]
hint = "It is a type of display, not a hardware device."
explanation = """
    CRT (Cathode Ray Tube) is a type of computer display that was common before the advent of LCD and LED displays.
"""

[[technology.questions]]
question = "Which of the following is a type of computer virus that spreads through email?"
answers = ["Worm"]
alternatives = ["Trojan", "Spyware", "Adware"]
hint = "This type of virus can replicate itself and spread rapidly through a network."
explanation = """
    A worm is a type of computer virus that spreads through email and other networked systems.
"""

[[technology.questions]]
question = "Which of the following is an example of a cloud-based application?"
answers = ["Google Docs"]
alternatives = ["Microsoft Word", "Photoshop", "VLC Player"]
hint = "This type of application allows users to collaborate in real-time and access their documents from anywhere."
explanation = """
    Google Docs is a cloud-based application that allows users to create and edit documents online.
"""

[generalknowledge]
label = "General Knowledge"

[[generalknowledge.questions]]
question = "What is the smallest planet in our solar system?"
answers = ["Mercury"]
alternatives = ["Mars", "Pluto", "Venus"]
hint = "It's named after the Roman messenger god."
explanation = """
    Mercury is the smallest planet in our solar system, and it is named after the Roman messenger god, who was known for his speed and agility.
"""

[[generalknowledge.questions]]
question = "Who was the first person to reach the summit of Mount Everest without using supplemental oxygen?"
answers = ["Tenzing Norgay"]
alternatives = ["Reinhold Messner", "Sir Edmund Hillary", "Junko Tabei"]
hint = " He was a Sherpa mountaineer from Nepal."
explanation = """
    Tenzing Norgay was a Sherpa mountaineer from Nepal who, along with Sir Edmund Hillary, was the first person to reach the summit of Mount Everest without using supplemental oxygen.
"""

[[generalknowledge.questions]]
question = "Which country is both the smallest country in the world by area and the most populous country in the world?"
answers = ["Vatican City"]
alternatives = ["Monaco", "San Marino", "Liechtenstein"]
hint = "It is located in Europe."
explanation = """
    Vatican City is the smallest country in the world by area, but it is also the most populous country in the world, with a population of approximately 800 people. It is located in Europe.
"""

[[generalknowledge.questions]]
question = "What is the only continent that is also a country?"
answers = ["Australia"]
alternatives = ["Europe", "Antarctica", "Africa"]
hint = "It is also known as the "Land Down Under"."
explanation = """
    Australia is the only continent that is also a country. It is located in the southern hemisphere and is also known as the "Land Down Under".
"""

[[generalknowledge.questions]]
question = "In what year did the Berlin Wall fall, leading to the reunification of Germany?"
answers = ["1989"]
alternatives = ["1987", "1991", "1993"]
hint = "It was towards the end of the Cold War."
explanation = """
    The Berlin Wall fell in 1989, leading to the reunification of Germany. This event was a significant milestone in the end of the Cold War.
"""

[[generalknowledge.questions]]
question = "Which African country was the first to gain independence from European colonial rule?"
answers = ["Ghana"]
alternatives = ["Kenya", "Egypt", "Tanzania"]
hint = "It gained independence in 1957."
explanation = """
    Ghana was the first African country to gain independence from European colonial rule. It gained independence in 1957.
"""

[[generalknowledge.questions]]
question = "Which artist painted the famous work "The Persistence of Memory", featuring melting clocks?"
answers = ["Salvador Dalí"]
alternatives = ["Pablo Picasso", "Vincent van Gogh", "Claude Monet"]
hint = "He was a Spanish surrealist painter."
explanation = """
    "The Persistence of Memory" is a famous work by Salvador Dalí, a Spanish surrealist painter. The painting features melting clocks and has become one of the most recognizable works of art in the world.
"""

[[generalknowledge.questions]]
question = "Which country is home to the world's tallest building, the Burj Khalifa?"
answers = ["United Arab Emirates"]
alternatives = ["United States", "China", "Saudi Arabia"]
hint = "It is located in the Middle East."
explanation = """
    The Burj Khalifa, the world's tallest building, is located in Dubai, United Arab Emirates. It stands at 828 meters tall.
"""

[[generalknowledge.questions]]
question = "Which element has the highest melting point?"
answers = ["Tungsten"]
alternatives = ["Carbon", "Titanium", "Platinum"]
hint = "It has an atomic number of 74."
explanation = """
    Tungsten has the highest melting point of any element, at 3422 degrees Celsius. It has an atomic number of 74.
"""

[[generalknowledge.questions]]
question = "Which African country is the most populous?"
answers = ["Nigeria"]
alternatives = ["Egypt", "Ethiopia", "Democratic Republic of the Congo"]
hint = "It has a population of over 200 million people."
explanation = """
    Nigeria is the most populous country in Africa, with a population of over 200 million people.
"""

[[generalknowledge.questions]]
question = "Which country is the world's largest producer of coffee?"
answers = ["Brazil"]
alternatives = ["Colombia", "Ethiopia", "Vietnam"]
hint = "It produces over one-third of the world's coffee."
explanation = """
    Brazil is the world's largest producer of coffee, producing over one-third of the world's coffee.
"""

[[generalknowledge.questions]]
question = "In what year did the Great Fire of London take place?"
answers = ["1666"]
alternatives = ["1605", "1707", "1752"]
hint = "It was a year after the end of the English Civil War."
explanation = """
    The Great Fire of London took place in 1666, a year after the end of the English Civil War. It destroyed over 13,000 houses and killed over 70 people.
"""

[[generalknowledge.questions]]
question = "Who was the first person to discover a planet using a telescope?"
answers = ["William Herschel"]
alternatives = ["Galileo Galilei", "Isaac Newton", "Johannes Kepler"]
hint = "He discovered Uranus."
explanation = """
    William Herschel was the first person to discover a planet using a telescope. He discovered Uranus in 1781.
"""

[[generalknowledge.questions]]
question = "Which river is the longest in the world?"
answers = ["Nile"]
alternatives = ["Amazon", "Mississippi", "Yangtze"]
hint = "It is located in Africa."
explanation = """
    The Nile is the longest river in the world, stretching over 6,600 kilometers through Africa.
"""

[[generalknowledge.questions]]
question = "What is the name of the instrument used to measure atmospheric pressure?"
answers = ["Barometer"]
alternatives = ["Thermometer", "Anemometer", "Hygrometer"]
hint = "It was invented by Evangelista Torricelli."
explanation = """
    A barometer is the instrument used to measure atmospheric pressure. It was invented by Evangelista Torricelli in the 17th century.
"""


[science]
label = "Science"

[[science.questions]]
question = "Which of the following is not a fundamental force of nature?"
answers = ["Centrifugal force"]
alternatives = ["Strong force", "Weak force", "Electromagnetic force"]
hint = "This force is often referred to as a "fake" force."
explanation = """
    The correct answer is (d) Centrifugal force. This is not a fundamental force, but rather an apparent force that arises from rotating frames of reference.
"""

[[science.questions]]
question = "Which element is used as a coolant in nuclear reactors?"
answers = ["Helium"]
alternatives = ["Uranium", "Plutonium", "Sodium"]
hint = "This element is a noble gas and is also used in balloons."
explanation = """
    Helium is used as a coolant in nuclear reactors because it is a stable and inert gas that does not react with other elements.
"""

[[science.questions]]
question = "What is the name of the process by which a solid changes directly into a gas??"
answers = ["Sublimation"]
alternatives = ["Vaporization", "Condensation", "Melting"]
hint = "This process is often used to make dry ice."
explanation = """
   Sublimation is the process by which a solid changes directly into a gas without going through the liquid phase.
"""

[[science.questions]]
question = "What is the smallest particle of an element that retains the chemical properties of that element?"
answers = ["Atom"]
alternatives = ["Molecule", "Electron", "Proton"]
hint = "This particle has a neutral charge."
explanation = """
    Atoms are the smallest particles of an element that retain the chemical properties of that element.
"""

[[science.questions]]
question = "What is the SI unit of pressure?"
answers = ["Pascal"]
alternatives = ["Newton", "Joule", "Watt"]
hint = "This unit is named after a French mathematician and physicist."
explanation = """
    The Pascal is the SI unit of pressure and is named after Blaise Pascal.
"""

[[science.questions]]
question = "Which of the following is a type of electromagnetic radiation that has a wavelength longer than visible light?"
answers = ["Infrared radiation"]
alternatives = ["X-rays", "Gamma rays", "Ultraviolet radiation"]
hint = "This radiation is often associated with warmth."
explanation = """
    Infrared radiation has a longer wavelength than visible light and is often associated with warmth and heat.
"""

[[science.questions]]
question = "What is the name of the process by which green plants use sunlight to synthesize food from carbon dioxide and water?"
answers = ["Photosynthesis"]
alternatives = ["Respiration", "Fermentation", "Combustion"]
hint = "This process releases oxygen as a byproduct."
explanation = """
    Photosynthesis process involves the conversion of light energy into chemical energy and releases oxygen as a byproduct.
"""

[[science.questions]]
question = "What is the boiling point of water at sea level in degrees Celsius?"
answers = ["100°C"]
alternatives = ["0°C", "212°C", "373°C"]
hint = "This temperature is commonly used as a reference point in temperature scales."
explanation = """
    This is the temperature at which water boils at sea level and is commonly used as a reference point in temperature scales.
"""

[[science.questions]]
question = "Which of the following is the most abundant gas in Earth's atmosphere?"
answers = ["Nitrogen"]
alternatives = ["Carbon dioxide", "Oxygen", "Argon"]
hint = "This gas makes up about 78% of the Earth's atmosphere."
explanation = """
    Nitrogen makes up about 78% of the Earth's atmosphere, followed by oxygen at 21%. The remaining 1% is made up of other gases.
"""

[[science.questions]]
question = "What type of rock is formed by the solidification of lava or magma?"
answers = ["Igneous"]
alternatives = ["Sedimentary", "Metamorphic", "Mineral"]
hint = "This type of rock is formed by the cooling and solidification of molten material."
explanation = """
    This type of rock is formed by the cooling and solidification of molten material. It is also known as extrusive or intrusive rock. Examples of igneous rocks include granite and basalt.
"""

[[science.questions]]
question = "Which of the following is an example of a nonrenewable resource?"
answers = ["Coal"]
alternatives = ["Wind", "Solar energy", "Biomass"]
hint = "This resource is finite and cannot be replenished within a human lifespan."
explanation = """
    Nonrenewable resources include fossil fuels such as coal, oil, and natural gas. These resources are finite and cannot be replenished within a human lifespan.
"""

[[science.questions]]
question = "What is the process by which an atom loses or gains electrons called?"
answers = ["Ionization"]
alternatives = ["Isotope", "Bonding", "Fusion"]
hint = "This process results in a change in the charge of the atom."
explanation = """
    When an atom loses or gains electrons, it becomes an ion with a positive or negative charge. This process is called ionization.
"""

[[science.questions]]
question = "Which of the following is a vector quantity?"
answers = ["Velocity"]
alternatives = ["Mass", "Temperature", "Volume"]
hint = "This quantity has both magnitude and direction."
explanation = """
    This quantity has both magnitude and direction. Examples of vector quantities include velocity, acceleration, and force.
"""

[[science.questions]]
question = "What is the process by which light bends as it passes through a medium with a different refractive index called?"
answers = ["Refraction"]
alternatives = ["Reflection", "Diffraction", "Dispersion"]
hint = "This process causes the apparent shift in position of objects seen through a lens."
explanation = """
    Refraction causes the apparent shift in position of objects seen through a lens. It is also responsible for the bending of light around the edges of a glass of water. Examples of refraction include the bending of light as it passes through a prism or a magnifying glass.
"""

[[science.questions]]
question = "What is the process by which a cell divides into two identical daughter cells called?"
answers = ["Mitosis"]
alternatives = ["Meiosis", "Cytokinesis", "Differentiation"]
hint = "This process results in the growth and repair of tissues in the body."
explanation = """
    During mitosis, the DNA in the parent cell is duplicated and divided equally between the two daughter cells. This process results in the growth and repair of tissues in the body.
"""